-- List of all active plugins and their git repository URLs for native package management
return {
  { name = "plenary.nvim", url = "https://github.com/nvim-lua/plenary.nvim" },
  { name = "nui.nvim", url = "https://github.com/MunifTanjim/nui.nvim", lazy = true },
  { name = "dropbar.nvim", url = "https://github.com/Bekaboo/dropbar.nvim" },
  { name = "nvim-web-devicons", url = "https://github.com/nvim-tree/nvim-web-devicons" },
  { name = "catppuccin", url = "https://github.com/catppuccin/nvim" },
  {
    name = "friendly-snippets",
    url = "https://github.com/rafamadriz/friendly-snippets",
    lazy = true,
  },
  { name = "blink.cmp", url = "https://github.com/saghen/blink.cmp", lazy = true },
  { name = "nvim-lspconfig", url = "https://github.com/neovim/nvim-lspconfig", lazy = true },
  { name = "mason.nvim", url = "https://github.com/williamboman/mason.nvim", lazy = true },
  {
    name = "mason-lspconfig.nvim",
    url = "https://github.com/williamboman/mason-lspconfig.nvim",
    lazy = true,
  },
  { name = "nvim-treesitter", url = "https://github.com/nvim-treesitter/nvim-treesitter" },
  { name = "rainbow-delimiters.nvim", url = "https://github.com/HiPhish/rainbow-delimiters.nvim" },
  {
    name = "nvim-ts-context-commentstring",
    url = "https://github.com/JoosepAlviste/nvim-ts-context-commentstring",
  },
  { name = "fzf-lua", url = "https://github.com/ibhagwan/fzf-lua", lazy = true },
  { name = "gitsigns.nvim", url = "https://github.com/lewis6991/gitsigns.nvim", lazy = true },
  {
    name = "nvim-highlight-colors",
    url = "https://github.com/brenoprata10/nvim-highlight-colors",
    lazy = true,
  },
  { name = "lazydev.nvim", url = "https://github.com/folke/lazydev.nvim", lazy = true },
  { name = "lualine.nvim", url = "https://github.com/nvim-lualine/lualine.nvim" },
  { name = "markdown.nvim", url = "https://github.com/tadmccorkle/markdown.nvim", lazy = true },
  { name = "markview.nvim", url = "https://github.com/OXY2DEV/markview.nvim", lazy = true },
  { name = "vim-visual-multi", url = "https://github.com/mg979/vim-visual-multi" },
  { name = "neogen", url = "https://github.com/danymat/neogen", lazy = true },
  { name = "neotest", url = "https://github.com/nvim-neotest/neotest", lazy = true },
  { name = "neo-tree.nvim", url = "https://github.com/nvim-neo-tree/neo-tree.nvim", lazy = true },
  { name = "none-ls.nvim", url = "https://github.com/nvimtools/none-ls.nvim", lazy = true },
  {
    name = "mason-null-ls.nvim",
    url = "https://github.com/jay-babu/mason-null-ls.nvim",
    lazy = true,
  },
  {
    name = "refactoring.nvim",
    url = "https://github.com/ThePrimeagen/refactoring.nvim",
    lazy = true,
  },
  { name = "async.nvim", url = "https://github.com/lewis6991/async.nvim", lazy = true },
  { name = "snacks.nvim", url = "https://github.com/folke/snacks.nvim" },
  { name = "nvim-surround", url = "https://github.com/kylechui/nvim-surround" },
  { name = "todo-comments.nvim", url = "https://github.com/folke/todo-comments.nvim", lazy = true },
  { name = "trouble.nvim", url = "https://github.com/folke/trouble.nvim", lazy = true },
  { name = "venn.nvim", url = "https://github.com/jbyuki/venn.nvim", lazy = true },
  { name = "which-key.nvim", url = "https://github.com/folke/which-key.nvim" },
  {
    name = "workspace-diagnostics.nvim",
    url = "https://github.com/artemave/workspace-diagnostics.nvim",
    lazy = true,
  },
  { name = "mini.ai", url = "https://github.com/echasnovski/mini.ai" },
  { name = "mini.align", url = "https://github.com/echasnovski/mini.align" },
  { name = "nvim-autopairs", url = "https://github.com/windwp/nvim-autopairs" },
  { name = "nvim-ts-autotag", url = "https://github.com/windwp/nvim-ts-autotag" },
  { name = "SchemaStore.nvim", url = "https://github.com/b0o/SchemaStore.nvim", lazy = true },
  { name = "bufferline.nvim", url = "https://github.com/akinsho/bufferline.nvim" },
  { name = "nvim-dap", url = "https://github.com/mfussenegger/nvim-dap", lazy = true },
  {
    name = "nvim-dap-python",
    url = "https://github.com/mfussenegger/nvim-dap-python",
    lazy = true,
  },
  {
    name = "mason-nvim-dap.nvim",
    url = "https://github.com/jay-babu/mason-nvim-dap.nvim",
    lazy = true,
  },
  { name = "nvim-dap-ui", url = "https://github.com/rcarriga/nvim-dap-ui", lazy = true },
  {
    name = "nvim-dap-virtual-text",
    url = "https://github.com/theHamsta/nvim-dap-virtual-text",
    lazy = true,
  },
  { name = "nvim-dap-lldb", url = "https://github.com/julianolf/nvim-dap-lldb", lazy = true },
  { name = "nvim-nio", url = "https://github.com/nvim-neotest/nvim-nio", lazy = true },
  { name = "flash.nvim", url = "https://github.com/folke/flash.nvim", lazy = true },
  {
    name = "indent-blankline.nvim",
    url = "https://github.com/lukas-reineke/indent-blankline.nvim",
    lazy = true,
  },
}
