-- List of all active plugins and their git repository URLs for native package management
local group = require("defaults").group

local function enabled(key) return group.plugins[key] == true end

local plugins = {
  { name = "plenary.nvim", key = "plenary", url = "https://github.com/nvim-lua/plenary.nvim" },
  { name = "nui.nvim", key = "nui", url = "https://github.com/MunifTanjim/nui.nvim", lazy = true },
  { name = "dropbar.nvim", key = "dropbar", url = "https://github.com/Bekaboo/dropbar.nvim" },
  {
    name = "nvim-web-devicons",
    key = "nvim_web_devicons",
    url = "https://github.com/nvim-tree/nvim-web-devicons",
  },
  { name = "catppuccin", key = "catppuccin", url = "https://github.com/catppuccin/nvim" },
  {
    name = "friendly-snippets",
    key = "friendly_snippets",
    url = "https://github.com/rafamadriz/friendly-snippets",
    lazy = true,
  },
  { name = "blink.cmp", key = "blink", url = "https://github.com/saghen/blink.cmp", lazy = true },
  {
    name = "nvim-lspconfig",
    key = "lspconfig",
    url = "https://github.com/neovim/nvim-lspconfig",
    lazy = true,
  },
  {
    name = "mason.nvim",
    key = "mason",
    url = "https://github.com/williamboman/mason.nvim",
    lazy = true,
  },
  {
    name = "mason-lspconfig.nvim",
    key = "mason_lspconfig",
    url = "https://github.com/williamboman/mason-lspconfig.nvim",
    lazy = true,
  },
  {
    name = "nvim-treesitter",
    key = "nvim_treesitter",
    url = "https://github.com/nvim-treesitter/nvim-treesitter",
  },
  {
    name = "rainbow-delimiters.nvim",
    key = "rainbow_delimiters",
    url = "https://github.com/HiPhish/rainbow-delimiters.nvim",
  },
  {
    name = "nvim-ts-context-commentstring",
    key = "nvim_ts_context_commentstring",
    url = "https://github.com/JoosepAlviste/nvim-ts-context-commentstring",
  },
  { name = "fzf-lua", key = "fzf", url = "https://github.com/ibhagwan/fzf-lua", lazy = true },
  {
    name = "gitsigns.nvim",
    key = "gitsigns",
    url = "https://github.com/lewis6991/gitsigns.nvim",
    lazy = true,
  },
  {
    name = "nvim-highlight-colors",
    key = "highlight_colors",
    url = "https://github.com/brenoprata10/nvim-highlight-colors",
    lazy = true,
  },
  {
    name = "lazydev.nvim",
    key = "lazydev",
    url = "https://github.com/folke/lazydev.nvim",
    lazy = true,
  },
  { name = "lualine.nvim", key = "lualine", url = "https://github.com/nvim-lualine/lualine.nvim" },
  {
    name = "markdown.nvim",
    key = "markdown",
    url = "https://github.com/tadmccorkle/markdown.nvim",
    lazy = true,
  },
  {
    name = "markview.nvim",
    key = "markview",
    url = "https://github.com/OXY2DEV/markview.nvim",
    lazy = true,
  },
  {
    name = "vim-visual-multi",
    key = "vim_visual_multi",
    url = "https://github.com/mg979/vim-visual-multi",
  },
  { name = "neogen", key = "neogen", url = "https://github.com/danymat/neogen", lazy = true },
  {
    name = "neotest",
    key = "neotest",
    url = "https://github.com/nvim-neotest/neotest",
    lazy = true,
  },
  {
    name = "neo-tree.nvim",
    key = "neotree",
    url = "https://github.com/nvim-neo-tree/neo-tree.nvim",
    lazy = true,
  },
  {
    name = "none-ls.nvim",
    key = "none_ls",
    url = "https://github.com/nvimtools/none-ls.nvim",
    lazy = true,
  },
  {
    name = "mason-null-ls.nvim",
    key = "mason_null_ls",
    url = "https://github.com/jay-babu/mason-null-ls.nvim",
    lazy = true,
  },
  {
    name = "refactoring.nvim",
    key = "refactoring",
    url = "https://github.com/ThePrimeagen/refactoring.nvim",
    lazy = true,
  },
  {
    name = "async.nvim",
    key = "async",
    url = "https://github.com/lewis6991/async.nvim",
    lazy = true,
  },
  { name = "snacks.nvim", key = "snacks", url = "https://github.com/folke/snacks.nvim" },
  { name = "nvim-surround", key = "surround", url = "https://github.com/kylechui/nvim-surround" },
  {
    name = "todo-comments.nvim",
    key = "todo_comments",
    url = "https://github.com/folke/todo-comments.nvim",
    lazy = true,
  },
  {
    name = "trouble.nvim",
    key = "trouble",
    url = "https://github.com/folke/trouble.nvim",
    lazy = true,
  },
  { name = "venn.nvim", key = "venn", url = "https://github.com/jbyuki/venn.nvim", lazy = true },
  { name = "which-key.nvim", key = "which_key", url = "https://github.com/folke/which-key.nvim" },
  {
    name = "workspace-diagnostics.nvim",
    key = "workspace_diagnostics",
    url = "https://github.com/artemave/workspace-diagnostics.nvim",
    lazy = true,
  },
  { name = "mini.ai", key = "mini_ai", url = "https://github.com/echasnovski/mini.ai" },
  { name = "mini.align", key = "mini_align", url = "https://github.com/echasnovski/mini.align" },
  { name = "nvim-autopairs", key = "autopairs", url = "https://github.com/windwp/nvim-autopairs" },
  {
    name = "nvim-ts-autotag",
    key = "nvim_ts_autotag",
    url = "https://github.com/windwp/nvim-ts-autotag",
  },
  {
    name = "SchemaStore.nvim",
    key = "schemastore",
    url = "https://github.com/b0o/SchemaStore.nvim",
    lazy = true,
  },
  {
    name = "bufferline.nvim",
    key = "bufferline",
    url = "https://github.com/akinsho/bufferline.nvim",
  },
  { name = "nvim-dap", key = "dap", url = "https://github.com/mfussenegger/nvim-dap", lazy = true },
  {
    name = "nvim-dap-python",
    key = "dap_python",
    url = "https://github.com/mfussenegger/nvim-dap-python",
    lazy = true,
  },
  {
    name = "mason-nvim-dap.nvim",
    key = "mason_nvim_dap",
    url = "https://github.com/jay-babu/mason-nvim-dap.nvim",
    lazy = true,
  },
  {
    name = "nvim-dap-ui",
    key = "dap_ui",
    url = "https://github.com/rcarriga/nvim-dap-ui",
    lazy = true,
  },
  {
    name = "nvim-dap-virtual-text",
    key = "dap_virtual_text",
    url = "https://github.com/theHamsta/nvim-dap-virtual-text",
    lazy = true,
  },
  {
    name = "nvim-dap-lldb",
    key = "dap_lldb",
    url = "https://github.com/julianolf/nvim-dap-lldb",
    lazy = true,
  },
  {
    name = "nvim-nio",
    key = "nvim_nio",
    url = "https://github.com/nvim-neotest/nvim-nio",
    lazy = true,
  },
  { name = "flash.nvim", key = "flash", url = "https://github.com/folke/flash.nvim", lazy = true },
  {
    name = "indent-blankline.nvim",
    key = "indent_blankline",
    url = "https://github.com/lukas-reineke/indent-blankline.nvim",
    lazy = true,
  },
}

return vim.tbl_filter(function(plugin) return enabled(plugin.key) end, plugins)
