#!/usr/bin/env zsh
# shellcheck disable=SC1071,SC1090,SC1091,SC2094,SC2102,SC2193,SC2203
#   ________         ______         __    __
#  |        \       /      \       |  \  |  \
#   \$$$$$$$$      |  $$$$$$\      | $$  | $$
#      /  $$       | $$___\$$      | $$__| $$
#     /  $$         \$$    \       | $$    $$
#    /  $$          _\$$$$$$\      | $$$$$$$$
#   /  $$___       |  \__| $$      | $$  | $$
#  |  $$    \       \$$    $$      | $$  | $$
#   \$$$$$$$$        \$$$$$$        \$$   \$$
#

OS="$(uname)"

# ---- Environment Variables -------------------------------------------------

export PATH="$HOME/.local/bin:$HOME/.local/share/nvim/mason/bin:$HOME/.cargo/bin:$HOME/go/bin:$HOME/.antigravity/antigravity/bin:$HOME/.spicetify:$PATH"

export ZSH="$HOME/.oh-my-zsh"
export DOTFILES_DIR="${DOTFILES_DIR:-${${(%):-%x}:A:h:h}}"
export EDITOR='nvim'
export VISUAL='nvim'

if [ "$OS" = "Linux" ]; then
  export QT_QPA_PLATFORMTHEME="qt5ct"
  export QT_SCREEN_SCALE_FACTORS="0.5"
  export QML_XHR_ALLOW_FILE_READ=1
  export LIBGUESTFS_BACKEND="direct"
  export CRYPTOGRAPHY_OPENSSL_NO_LEGACY=1
elif [ "$OS" = "Darwin" ]; then
  export HOMEBREW_NO_AUTO_UPDATE=1
  export HOMEBREW_NO_ENV_HINTS=1
  export MAGICK_HOME="/opt/local"
  # allow use of gnu tools
  export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
fi

# ---- Terminal Settings -----------------------------------------------------

export DISABLE_MAGIC_FUNCTIONS="true"
export COMPLETION_WAITING_DOTS="true" # show command is auto completing
export HISTSIZE=10000                 # big history
export SAVEHIST=10000
export DISABLE_UNTRACKED_FILES_DIRTY="true" # stops git status from checking untracked files

autoload -U edit-command-line # edit command in vim
fpath=(~/.zfunc "${fpath[@]}")
autoload -U bashcompinit
bashcompinit
zle -N edit-command-line

# disable ctrl-s and q
if [[ -n ${TTY:-} && $+commands[stty] == 1 ]]; then
  stty -ixon <"$TTY" >"$TTY"
fi

set -o ignoreeof
unalias -a # remove preset aliases

# ---- Plugins ---------------------------------------------------------------

plugins=(
  git
  pip
  copyfile
  command-not-found
  colored-man-pages
  history-substring-search
  last-working-dir
  safe-paste
  zsh-interactive-cd
  zsh-autosuggestions
  zsh-syntax-highlighting
  vi-mode
)

# ---- Load Scripts ----------------------------------------------------------

if [ "$OS" = "Darwin" ] && command -v brew >/dev/null 2>&1; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

source "$ZSH"/oh-my-zsh.sh >/dev/null 2>&1 # load oh-my-zsh

loadpath="$DOTFILES_DIR/home/scripts"
if [ -f "$loadpath/aliasList.sh" ]; then # load aliases
  # shellcheck source=/dev/null
  source "$loadpath/aliasList.sh"
fi
if [ -f "$loadpath/commands.sh" ]; then # load commands
  # shellcheck source=/dev/null
  source "$loadpath/commands.sh"
fi

autoload -U compinit
compinit

# ---- Keybindings -----------------------------------------------------------

bindkey '^d' autosuggest-accept
bindkey '^k' edit-command-line

# ---- Cross-Platform Tool Setup ---------------------------------------------

LS_COLORS="$(vivid generate catppuccin-mocha)"
export LS_COLORS

eval "$(zoxide init zsh)"

eval "$(starship init zsh)"

eval "$(register-python-argcomplete pipx)"

if [ -f ~/.fzf.zsh ]; then
  # shellcheck source=/dev/null
  source ~/.fzf.zsh # load fzf
fi

# shellcheck disable=SC1090
source <(fzf --zsh)

# Miniconda
if [ -f /opt/miniconda3/etc/profile.d/conda.sh ]; then
  # shellcheck source=/dev/null
  source /opt/miniconda3/etc/profile.d/conda.sh
elif [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
  # shellcheck source=/dev/null
  source "$HOME/miniconda3/etc/profile.d/conda.sh"
fi

# NVM (Node Version Manager)
export NVM_DIR="$HOME/.nvm"
if [ "$OS" = "Darwin" ] && [ -n "${HOMEBREW_PREFIX:-}" ]; then
  [ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && source "$HOMEBREW_PREFIX/opt/nvm/nvm.sh"
  [ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && source "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm"
else
  [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
  [ -s "$NVM_DIR/bash_completion" ] && source "$NVM_DIR/bash_completion" # This loads nvm bash_completion
fi

NODE_PATH="${NODE_PATH:-}:$(npm root -g)"
export NODE_PATH

# ---- OS-Specific Commands --------------------------------------------------

if [ "$OS" = "Linux" ]; then
  if [ -f /usr/share/doc/pkgfile/command-not-found.zsh ]; then
    # shellcheck source=/dev/null
    source /usr/share/doc/pkgfile/command-not-found.zsh
  fi
elif [ "$OS" = "Darwin" ]; then
  ulimit -Sn unlimited && ulimit -Sl unlimited
fi
