[misc]
assume_yes = true
disable = []
no_retry = true
pre_sudo = true
cleanup = true
no_self_update = false

[git]
max_concurrency = 10

[brew]
greedy_cask = true
autoremove = true

[linux]
arch_package_manager = "yay"

[windows]
self_rename = true
