source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/monitors.conf

$font_family = JetBrainsMono Nerd Font
$box_bg = rgba(40, 40, 46, 0.9)
$box_border = rgba($mutedAlphaff)
$time = cmd[update:1000] echo "$(date +"%H:%M")"

general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/chilly/code/dotfiles/home/walls/wp4892339.jpg
    blur_passes = 3
    blur_size = 8
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# ==========================================
# 1440p G5 (STANDARD SIZE)
# ==========================================

# Password Input
input-field {
    monitor = $monitor2
    size = 250, 60
    outline_thickness = 2
    dots_center = true
    outer_color = $box_border
    inner_color = $box_bg
    font_color = $text
    font_family = $font_family Bold
    placeholder_text = <i><span foreground="##$purpleAlpha">Password...</span></i>
    fade_on_empty = false
    position = 0, -120
    halign = center
    valign = center
}

# Time
label {
    monitor = $monitor2
    text = $time
    color = $peach
    font_size = 120
    font_family = $font_family ExtraBold
    position = 0, -300
    halign = center
    valign = top
}

# Welcome
label {
    monitor = $monitor2
    text = Welcome back, Pranay
    color = $text
    font_size = 25
    font_family = $font_family Bold
    position = 0, -40
    halign = center
    valign = center
}

# ==========================================
# 4K OLED (150% UPSCALE)
# ==========================================

input-field {
    monitor = $monitor1
    size = 375, 90
    outline_thickness = 3
    dots_center = true
    outer_color = $box_border
    inner_color = $box_bg
    font_color = $text
    font_family = $font_family Bold
    placeholder_text = <i><span foreground="##$purpleAlpha">Password...</span></i>
    fade_on_empty = false
    position = 0, -180
    halign = center
    valign = center
}

# Time
label {
    monitor = $monitor1
    text = $time
    color = $peach
    font_size = 180
    font_family = $font_family ExtraBold
    position = 0, -450
    halign = center
    valign = top
}

# Welcome
label {
    monitor = $monitor1
    text = Welcome back, Pranay
    color = $text
    font_size = 38
    font_family = $font_family Bold
    position = 0, -60
    halign = center
    valign = center
}
