monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-SMSL_SMSL_UAC1-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
      }
    }
  }
]
