monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-SMSL_SMSL_UAC1-00"
      }
    ]
    actions = {
      update-props = {
        api.alsa.use-ucm = false
      }
    }
  }
]
