general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # Lock before the system goes to sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # Wake up screens when waking up from sleep
}

# Lock the screen after 5 minutes (300 seconds)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn off the OLED/LCD panels after 5.5 minutes (330 seconds)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
