source = ~/.config/hypr/monitors.conf
splash = false
ipc = on

wallpaper {
    monitor = $monitor1
    path = /home/chilly/Pictures/walls/du3gwu0y5rm51.jpg
    fit_mode = cover
}

wallpaper {
    monitor = $monitor2
    path = /home/chilly/Pictures/walls/du3gwu0y5rm51.jpg
    fit_mode = cover
}
