splash = false
ipc = on

wallpaper {
    monitor = desc:Microstep MPG321UX OLED 0x01010101
    path = /home/chilly/Pictures/walls/minimalist/1095285.jpg
    fit_mode = cover
}

wallpaper {
    monitor = desc:Samsung Electric Company Odyssey G5 HNBY700285
    path = /home/chilly/Pictures/walls/minimalist/1095285.jpg
    fit_mode = cover
}
