local M = {}

-- Null-ls sources list
M.setup_sources = function(b)
	return {
		b.formatting.clang_format,
		b.formatting.stylua,
		b.formatting.cbfmt,
		b.formatting.shfmt,
		b.formatting.gofumpt,
		b.formatting.black,
		b.formatting.cmake_format,
		b.formatting.prettierd.with({
			filetypes = {
				"javascript",
				"javascriptreact",
				"typescript",
				"typescriptreact",
				"html",
				"css",
			},
		}),
		b.formatting.verible_verilog_format,
		b.diagnostics.verilator,
		b.diagnostics.checkmake,
		b.diagnostics.cmake_lint,
		b.diagnostics.pylint,
		b.diagnostics.revive,
		b.code_actions.gitsigns,
		b.code_actions.gomodifytags,
		b.code_actions.refactoring,
	}
end

-- Auto install Mason sources
M.ensure_installed = {
	treesitter = {
		"asm",
		"bash",
		"c",
		"cmake",
		"comment",
		"cpp",
		"css",
		"csv",
		"cuda",
		"diff",
		"disassembly",
		"dockerfile",
		"xml",
		"gitattributes",
		"gitcommit",
		"gitignore",
		"glsl",
		"go",
		"gomod",
		"gosum",
		"html",
		"hyprlang",
		"java",
		"javascript",
		"jsdoc",
		"json",
		"json5",
		"jsonc",
		"latex",
		"lua",
		"luap",
		"luau",
		"make",
		"markdown",
		"meson",
		"ninja",
		"objdump",
		"printf",
		"python",
		"regex",
		"ron",
		"rust",
		"scss",
		"toml",
		"tsx",
		"verilog",
		"wgsl",
		"yaml",
	},
	null_ls = {
		"cbfmt",
		"clangd",
		"codelldb",
		"css_lsp",
		"debugpy",
		"delve",
		"gofumpt",
		"goimports_reviser",
		"gopls",
		"html_lsp",
		"jq",
		"json_lsp",
		"lua_language_server",
		"prettierd",
		"basedpyright",
		"shfmt",
		"stylua",
		"svlangserver",
		"typescript_language_server",
		"verible",
		"wgsl_analyzer",
	},
	dap = {
		"python",
	},
}

-- setup formatting servers
M.formatting_servers = {
	["null-ls"] = {
		"lua",
		"javascript",
		"javascriptreact",
		"typescript",
		"typescriptreact",
		"html",
		"css",
		"json",
		"python",
		"sh",
		"bash",
		"zsh",
		"go",
		"cpp",
		"c",
		"cmake",
		"systemverilog",
		"markdown",
	},
}

-- default value is true for all
M.group = {
	plugins = {
		ai = true,
		align = true,
		alpha = true,
		asyncrun = true,
		autotag = true,
		autosave = true,
		bufferline = true,
		catppuccin = true,
		cmp = true,
		copilot = true,
		dap = true,
		dap_python = true,
		dressing = true,
		dropbar = true,
		gitsigns = true,
		highlight_colors = true,
		hop = true,
		illuminate = true,
		image = true,
		indent_blankline = true,
		lazydev = true,
		lsp_zero = true,
		lualine = true,
		markdown = true,
		markdown_render = true,
		move = true,
		multicursor = true,
		nabla = true,
		neogen = true,
		neoscroll = true,
		neotest = true,
		neotree = true,
		noice = true,
		none_ls = true,
		notify = true,
		obsidian = true,
		possession = true,
		project = true,
		refactor = true,
		rustacean = true,
		scope = true,
		surround = true,
		telescope = true,
		todo_comments = true,
		toggleterm = true,
		autopairs = true,
		rainbow = true,
		treesitter = true,
		trouble = true,
		ufo = true,
		venn = true,
		virt_column = true,
		whichkey = true,
		workspace_diagnostics = true,
		zen = true,
	},
	autocommands = {
		trailing_whitespace = true,
		remember_file_state = true,
		term_spelling = true,
		number = true,
	},
}

M.colorscheme = "catppuccin"

return M
