#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# auto float non-resizable windows
yabai -m signal --add event=window_created action='
  yabai -m query --windows --window $yabai_window_id | jq -er ".\"can-resize\" or .\"is-floating\"" || \
 yabai -m window $yabai_window_id --toggle float --layer above --grid 4:4:1:1:2:2
'

yabai -m rule --add app="^({Preview|Activity Monitor|App Store|Calculator|Spotify|System Preferences|System Settings|zoom.us|Steam|Raycast|Settings|Spotlight)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m config external_bar all:40:0 \
	mouse_follows_focus off \
	focus_follows_mouse autofocus \
	window_zoom_persist off \
	window_placement second_child \
	window_shadow float \
	window_opacity off \
	window_topmost on \
	window_opacity_duration 0.2 \
	active_window_opacity 1.0 \
	insert_feedback_color 0xff9dd274 \
	split_ratio 0.50 \
	auto_balance off \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	\
	top_padding 0 \
	bottom_padding 8 \
	left_padding 8 \
	right_padding 8 \
	window_gap 12

yabai -m config layout bsp
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

echo "yabai configuration loaded.."
