# BY Tech Gaming Keyboard's primary keyboard interface.
[ids]
258a:010c:3d952825

[main]
# Exchange Caps Lock with left Control, and Super/Win with left Alt.
capslock = layer(control)
leftcontrol = capslock
leftalt = layer(meta)
leftmeta = layer(alt)
