# __    __  ______  ________  ________  __      __
#
# |  \  /  \|      \|        \|        \| \    /  \
# | $$ /  $$ \$$$$$$ \$$$$$$$$ \$$$$$$$$ \$$\  /  $$
# | $$/  $$   | $$     | $$      | $$     \$$\/  $$
# | $$  $$    | $      | $$      | $$      \$$  $$
# | $$$$$\    | $$     | $$      | $$       \$$$$
# | $$ \$$\  _| $$_    | $$      | $$       | $$
# | $$  \$$\|   $$ \   | $$      | $$       | $$
# \$$   \$$ \$$$$$$    \$$       \$$        \$$


# ---- Visuals ----------------------------------------------------------------

font_family JetBrainsMono Nerd Font
italic_font auto
bold_font auto
bold_italic_font auto
disable_ligatures cursor
background_opacity 0.98

# ---- Color Palette ----------------------------------------------------------

foreground              #e6dcd1
background              #28282e
selection_foreground    #28282e
selection_background    #a28ba6

cursor                  #f2a284
cursor_text_color       #28282e

url_color               #e6b473

active_border_color     #f2a284
inactive_border_color   #6b6475
bell_border_color       #e6b473

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #28282e
active_tab_background   #f2a284
inactive_tab_foreground #e6dcd1
inactive_tab_background #15131c
tab_bar_background      #15131c

# Colors for marks
mark1_foreground #28282e
mark1_background #6a859c
mark2_foreground #28282e
mark2_background #a28ba6
mark3_foreground #28282e
mark3_background #e6b473

# The 16 terminal colors

# black
color0 #28282e
color8 #6b6475

# red
color1 #c25d5d
color9 #d37363

# green
color2  #8b9a73
color10 #a1b088

# yellow
color3  #e6b473
color11 #eebd8a

# blue
color4  #6a859c
color12 #809ebb

# magenta
color5  #a28ba6
color13 #bcadd4

# cyan
color6  #7b9ea3
color14 #92bac0

# white
color7  #e6dcd1
color15 #f5ebe0

# ---- General Settings -------------------------------------------------------

scrollback_lines 10000
strip_trailing_spaces smart
enable_audio_bell no
initial_window_width  1920
initial_window_height 1200
confirm_os_window_close 0
tab_bar_edge top
tab_bar_style powerline
tab_bar_align center
update_check_interval 0
tab_bar_min_tabs 2
window_padding_width 6
hide_window_decorations titlebar-only
allow_remote_control yes
listen_on unix:/tmp/mykitty
shell_integration no-sudo
macos_option_as_alt yes

# ---- Keybindings ------------------------------------------------------------

map ctrl+shift+j neighboring_window bottom
map ctrl+shift+k neighboring_window top
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+; next_layout

map ctrl+shift+] next_tab
map ctrl+shift+[ previous_tab
