#!/usr/bin/env bash

DOTFILES_DIR="${DOTFILES_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
DOTFILES_HOME_DIR="$DOTFILES_DIR/home"
DOTFILES_CONFIG_DIR="$DOTFILES_HOME_DIR/config"
DOTFILES_SCRIPTS_DIR="$DOTFILES_HOME_DIR/scripts"
DOTFILES_WALLPAPERS_DIR="$DOTFILES_HOME_DIR/walls"

THEME_JSON="$DOTFILES_SCRIPTS_DIR/theme.json"

HYPR_CONFIG_DIR="$DOTFILES_CONFIG_DIR/hypr"
HYPRPAPER_CONFIG="$HYPR_CONFIG_DIR/hyprpaper.conf"
HYPRLOCK_CONFIG="$HYPR_CONFIG_DIR/hyprlock.conf"

AUTO_THEME_SCRIPT="$DOTFILES_SCRIPTS_DIR/auto_theme.py"
APPLY_THEME_SCRIPT="$DOTFILES_SCRIPTS_DIR/apply_theme.py"
SET_WALLPAPER_SCRIPT="$DOTFILES_SCRIPTS_DIR/set_wallpaper.sh"
